### ISSUE TITLE
TypeError when using GenericForeignKey

### ISSUE THREAD

**Issue by dperetti** [eamigo86/graphene-django-extras#10]
`'<' not supported between instances of 'GenericForeignKey' and 'DateTimeField'`.

The exception is triggered here : https://github.com/eamigo86/graphene-django-extras/blob/master/graphene_django_extras/utils.py#L22 when using a type like this :
```python
class CommentType(DjangoObjectType):
    class Meta:
        model = Comment
```

For a model like this:

```python
class Comment(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE,)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    body = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
```

**Comment by eamigo86** [comment]
Hi @dperetti, sorry for the delay, is that unfortunately I do not have 24h internet connection.
Can you tell me what version of _graphene-django-extras_ you are using. Because I tested with graphene-django-extras>0.0.4 and work fine. The last version is [0.1.0.alpha4](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.1.0-alpha4) of today.

**Comment by dperetti** [comment]
Hey sorry for the delay too. Working on this only 3 days a week :-)
Unfortunately the issue is still present in 0.1.0a9. The only one that works is 0.0.2.
0.0.3 was working too but apparently it disappeared.
By the way it would be great to have a pytest based test suite with a django sample project !
If you're willing to, I can help to set one up.

**Comment by dperetti** [comment]
Also tried  from the master (053c6f9627c4152509831e91d18fe84e14e20e44) with no avail.

**Comment by dperetti** [comment]
The quick fix that works for me is to exclude virtual_fields from the sorting, like this:
```
        in sorted(list(model._meta.fields) +
                  list(model._meta.local_many_to_many)) + list(model._meta.virtual_fields)
```

**Comment by eamigo86** [comment]
Hello @dperetti, I would like you to help me to set a pytest based test suite with a sample project up.
I have tried the same example that you use and that throws the exception and works well, what version of Django are you using?

**Comment by eamigo86** [comment]
Hi @dperetti, You could try version [**0.1.0alpha11**](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.1.0-alpha11) and tell me if the bug is fixed?

**Comment by dperetti** [comment]
That one works ! (I was using Django 1.11.2).
I'll get back to you soon with a pytest setup !
