### ISSUE TITLE
Aggregate functions/queryset-level field

### ISSUE THREAD

**Issue by pheel** [eamigo86/graphene-django-extras#108]
Thanks for this great package! What would be the best strategy to implement a field like `oldestUser` in the hypothetical query below?

```
allUsers(username_Icontains:"john"){
  results(limit:5, offset:5){
    username                       (property of entity)
    age                            (property of entity)
  }
  totalCount                       (property of queryset)
  oldestUser                       (property of queryset)
}
```

I looked at the DjangoListObjectType class and found that "totalCount" comes from _meta.fields, but I don't understand how that field actually gets connected to a queryset count value. Ideally, I would like to init UserListType with an additional dict that lists arbitrary functions over querysets.

```
def oldestUser(qs):
  return max([user.age for user in qs])

class UserListType(DjangoListObjectType):
  class Meta:
    model = User
    extra_fields = {
      'oldestUser': oldestUser
    }
```

**Comment by pheel** [comment]
https://github.com/pheel/graphene-django-extras/commit/d18d822c9408854544dda03b89964c7107187464

**Comment by PriyatamNayak** [comment]
@pheel Want to use moving avg or mean ,how can we achieve it?
can you share a sample code?
