### ISSUE TITLE
name 'LimitOffsetGraphqlPagination' is not defined

### ISSUE THREAD

**Issue by dperetti** [eamigo86/graphene-django-extras#11]
Hey,
I'm setting up a basic sample project for testing purposes in a fork of your repository, and I stumbled upon this issue when using LimitOffsetGraphqlPagination here: https://github.com/dperetti/graphene-django-extras/blob/7c9e38b9136681cd6522744eb151fbefe0d483aa/sampleproject/sampleproject/schema.py#L69
Looks very much like a circular import issue. 
Can you have a look ?

**Comment by eamigo86** [comment]
Hi @dperetti, in last commit I fixed it and in next version it will be available.

**Comment by dperetti** [comment]
Cool! Did you check the result as well ? Because yesterday night I kinda found a workaround like yours so it no longer crashed, but the result was not ok (empty or bogus if I can recall).

**Comment by eamigo86** [comment]
Well the truth is that the error was eliminated but the result is not what was expected, at least in the filtering part, I am working on the next version in which the filtering will be correct

**Comment by eamigo86** [comment]
Hi @dperetti in last release 0.1.1 this error was fixed, please test it.

**Comment by dperetti** [comment]
@eamigo86 yeah it seems to work! Meanwhile I've set up a very basic test project with 3 test runs at the moment. I'll add more and do a pull request, unless you'd like to merge it early.
In the tests branch: https://github.com/dperetti/graphene-django-extras/tree/tests
