### ISSUE TITLE
Make update for graphene-django V2.3.2

### ISSUE THREAD

**Issue by ijharulislam** [eamigo86/graphene-django-extras#111]
Graphene-dajngo released a new version 2.3.2. graphene-django-extras is not working with recent realese.
Facing this issue:

```
 from graphene_django_extras import DjangoFilterPaginateListField
/usr/local/lib/python3.6/site-packages/graphene_django_extras/__init__.py:8: in <module>
    from .mutation import DjangoSerializerMutation
/usr/local/lib/python3.6/site-packages/graphene_django_extras/mutation.py:8: in <module>
    from graphene_django.rest_framework.types import ErrorType
E   ImportError: cannot import name 'ErrorType'
```

**Comment by nuarhu** [comment]
is fixed in/with https://github.com/eamigo86/graphene-django-extras/pull/110

**Comment by drdla** [comment]
I just researched the problem and found that bugfix in master.
But the last release is from January.
Is it possible to release that fix in the next couple of days?
Right now we have to keep our dependencies outdated because the current versions are breaking.

**Comment by eamigo86** [comment]
Hello friends, thank you for your feedback. I have updated the version in Pypi (0.4.5)
