### ISSUE TITLE
[INVALID] DjangoFilterListField on reverse relations?

### ISSUE THREAD

**Issue by karlosss** [eamigo86/graphene-django-extras#114]
Hi,

is it somehow possible to use `DjangoFilterListField` on reverse relations? Let me show you an example:

```
class Book(Model):
    name = CharField()
    publisher = ForeignKey(Publisher, related_name="books")

class Publisher(Model):
    name = CharField()

class BookType(DjangoObjectType):
    class Meta:
        model = Book
        filter_fields = ...
    ...

class PublisherType(DjangoObjectType):
    class Meta:
        model = Publisher
        filter_fields = ...
    ...
```
I would expect such a query

```
query{
  publishers{
    id
    name
    books(name_Contains: "a"){
      id
      name
    }
  }
}
```

to list all publishers and for each one, all their books whose name contains an `a`. Instead, I get this:

```
{
  "errors": [
    {
      "message": "Cannot query field \"books\" on type \"PublisherType\".",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ]
    }
  ]
}
```

My fault, or a bug? The system seems to ignore reverse relations completely. If you need any more code, just please ask. Thanks a lot!

**Comment by karlosss** [comment]
I am just stupid, everything works as expected. Sorry!

**Comment by grusirna** [comment]
Could you tell me how to do it?

**Comment by karlosss** [comment]
Unless you tamper with the library like I did, it shall work out of the box. It's quite hard to guess without seeing any code or concrete issues.

**Comment by sbernier1** [comment]
Hi, it doesn't work for me. I can add arguments to both separately, but not combined.

I have those 2 queries:

```
publishers = DjangoFilterListField(PublisherType)
books = DjangoFilterListField(BookType)
```

and I can query both like this:
```
publishers(name_Icontains:"r")
  {
    name
  }
  books(name_Icontains:"r")
  {
    name
  }
```

but this won't work:
```
publishers
  {
    name
    books(name_Icontains:"r")
    {
        name
    }
  }
  
```

it gives me this error: `"Unknown argument \"name_Icontains\" on field \"books\" of type \"publishers\"."` 

can you please help?

Thank you.
