### ISSUE TITLE
Access @property attributes when using DjangoSerializerType 

### ISSUE THREAD

**Issue by fabienheureux** [eamigo86/graphene-django-extras#119]
Hi 👋, 

It seems like it is not possible to access `@property` attributes defined in models if queries are defined using `DjangoSerializerType`.

Here is a summarized version of the code I am trying to use 

```python
# schema.py
class ContactModelType(DjangoSerializerType):
    name = graphene.String()

    def resolve_name(self, info):
        return self.name

    class Meta:
        model = Contact
        # tried explicitely fields = ('name',) here but this did not help
        serializer_class = ContactSerializer
        pagination = LimitOffsetGraphqlPagination(
            default_limit=25, ordering="-created_at")
```
```python
# serializers.py
class ContactSerializer(serializers.ModelSerializer):
    name = serializers.SerializerMethodField()

    class Meta:
        model = Contact
        fields = '__all__' # tried explicitely fields = ('name',) here but this did not help

    def get_name(self):
        return self.name
```
```python
# models.py
class Contact(models.Model): 
    first_name = models.CharField()
    last_name = models.CharField()
    
    @property
    def name(self):
        return "%s %s" % (self.first_name, self.last_name)
```

I get each time the following error: `Cannot query field \"name\" on type \"ContactGenericType\"`
If I use DjangoListObjectField method to define my models queries, it works properly.

By the way: I think that define both `resolve` method on the `ContactModelType` and `get` method on the `ContactSerializer` are useless, but I tried both, only each one of them, and none work 🙄. 

Is there a way to get it to work ? 
Thanks a lot in advance 😎

**Comment by dpretty** [comment]
I've just been trying to figure this out as well.

Something which worked for me was to create a separate DjangoObjectType with the property defined.

```
class ContactDjangoObjectType(DjangoObjectType):
    name = graphene.String()

    class Meta:
        model = Contact
```

And then the DjangoSerializerType seems to pick it up as the registered type. It seems a bit superfluous, perhaps there's a way to register ContactModelType as the type to be returned for queries but don't have time to check that right now...

**Comment by flyte** [comment]
That doesn't appear to work for me:

```python
class MemberDjangoObjectType(DjangoObjectType):
    class Meta:
        model = Member

    name = graphene.String()


class MemberSerializer(ModelSerializer):
    class Meta:
        model = Member
        fields = "__all__"

    # Tried with and without this field and get_name()
    name = serializers.SerializerMethodField()

    def get_name(self, instance):
        return instance.name


class MemberModelType(DjangoSerializerType):
    class Meta:
        serializer_class = MemberSerializer
        pagination = LimitOffsetGraphqlPagination(default_limit=25, ordering="id")
        input_field_name = "member"
```

Should this magically show up, or do I need to reference `MemberDjangoObjectType` somewhere? Cheers

**Comment by flyte** [comment]
Ah, I was importing the `DjangoObjectType` from `graphene_django` instead of `graphene_django_extras`. Hit some other problems though, which I'm still working through.
