### ISSUE TITLE
Mutation error with DjangoSerializerType

### ISSUE THREAD

**Issue by Snake575** [eamigo86/graphene-django-extras#12]
Hi, I encountered an error calling mutations on a model implementing `DjangoSerializerType`
![image](https://user-images.githubusercontent.com/4157289/32685798-37bc4400-c677-11e7-89e0-a90c96ad8ec7.png)

It works fine with `DjangoSerializerMutation`
![image](https://user-images.githubusercontent.com/4157289/32685788-083d20fa-c677-11e7-9a1a-d97fe30bb420.png)

It seems that `ok` and `errors` aren't present on the mutation output on `DjangoSerializerType`

**Comment by eamigo86** [comment]
Hi @Snake575, thanks for report this, on next version this bug will be fixed.

**Comment by eamigo86** [comment]
Hi @Snake575 test with last version: [0.1.2](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.1.2)

**Comment by Snake575** [comment]
@eamigo86 now it works!

Thanks!!!
