### ISSUE TITLE
Potential dependency conflicts between graphene-django-extras and graphql-core

### ISSUE THREAD

**Issue by NeolithEra** [eamigo86/graphene-django-extras#131]
Hi, as shown in the following full dependency graph of **_graphene-django-extras_**, **_graphene-django-extras_** requires **_graphql-core >=2.2.1,<3.0.0_**, **_graphene-django-extras_** requires **_graphene >=2.1.8,<3.0.0_** (**_graphene 2.1.8_** will be installed, i.e., the newest version satisfying the version constraint), and directed dependency **_graphene 2.1.8_** transitively introduces **_graphql-core >=2.1,<3.0.0_**.

Obviously, there are multiple version constraints set for **_graphql-core_** in this project. However, according to pip's _“first found wins”_ installation strategy, **_graphql-core 2.3.2_** (i.e., the newest version satisfying constraint **_>=2.2.1,<3.0.0_**) is the actually installed version.

Although the first found package version **_graphql-core 2.3.2_** just satisfies the later dependency constraint （**_graphql-core >=2.2.1,<3.0.0_**), such installed version is very close to the upper bound of the version constraint of graphql-core specified by **_graphene 2.1.8_**. 

Once **_graphene_** upgrades，its newest version will be installed. Therefore, it will easily cause a dependency conflict (build failure), if the upgraded **_graphene_** version introduces a higher version of **_graphql-core_**, violating its another version constraint **_>=2.2.1,<3.0.0_**.

According to the release history of graphene, it habitually upgrates Graphql-core in its recent releases. For instance, graphene 2.0.0 upgrated Graphql-core’s constraint from >=1.2.dev to >=2.0.dev,graphene 2.1.3 upgrated Graphql-core’s constraint from >=2.0,<3.0to >=2.1,<3.0 and graphene next version upgrated Graphql-core’s constraint from >=2.1,<3.0 to >=3.1.0b1,<4. 

As such, it is a warm warning of a potential dependency conflict issue for graphene-django-extras.

### Dependency tree
```
graphene-django-extras - 0.4.8
| +- django-filter(install version:2.2.0 version range:>=2.2.0,<3.0.0)
| | +- django(install version:3.0.5 version range:>=1.11)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- djangorestframework(install version:3.11.0 version range:*)
| | +- django(install version:3.0.5 version range:>=1.11)
| | | +- asgiref (install version: version range:=3.2)
| | | +- pytz(install version:2019.3 version range:*)
| | | +- sqlparse (install version:0.3.1 version range:>=0.2.2)
| +- graphene(install version:2.1.8 version range:>=2.1.8,<3.0.0)
| | +- aniso8601(install version:7 version range:>=3,<=7)
| | +- graphql-core(install version:2.3.2 version range:<3,>=2.1)
| | +- graphql-relay(install version:2.0.1 version range:<3,>=2)
| | | +- graphql-core(install version:2.3.2 version range:>=2.2,<3)
| | | +- promise(install version:2.3 version range:>=2.2,<3)
| | | | +- six(install version:1.14.0 version range:*)
| | | | +- typing(install version:3.7.4.1 version range:>=3.6.4)
| | | +- six(install version:1.14.0 version range:>=1.12)
| | +- six(install version:1.14.0 version range:>=1.10.0,<2)
| +- graphene-django(install version:2.10.0 version range:>=2.5.0,<3.0.0)
| +- graphql-core(install version:2.3.2 version range:>=2.2.1,<3.0.0)
| +- python-dateutil(install version:2.8.1 version range:>=2.8.0,<3.0.0)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Loosen the version range of **_graphql-core_** to be **_>=2.2.1_**.
2.	Remove your direct dependency **_graphql-core_**, and use the **_graphql-core_** transitively introduced by **_graphene_**.
3.	Change your direct dependency **_graphene_** to be **_<=2.1.8_**.
@eamigo86  Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by eamigo86** [comment]
Hello @NeolithEra, first of all, thank you very much for the analysis carried out on the possible problem of module dependencies. As for the question, I think the best solution would be to apply variants 1 and 3 together, leaving only graphene<=2.1.8 as a dependency.

Likewise, I will start working on a new version of the module, to correct some bugs, add some new features, implement better support for Subscriptions, add better integration with third-party packages, and possibly this update is for use only with Django>=2.0 and Python>=3.6.

So any help will be welcome :)
