### ISSUE TITLE
Couldn't make filters work

### ISSUE THREAD

**Issue by MiltonLn** [eamigo86/graphene-django-extras#17]
Hey! Thanks for this amazing utility, definitely it makes using graphene a lot easier with Django.

I'm having this error when trying to implement a filtered query:

```python
Traceback (most recent call last):
  File "/home/miltonln/Proyectos/Swapps/accountant-venv/lib/python3.6/site-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/home/miltonln/Proyectos/Swapps/accountant-venv/lib/python3.6/site-packages/graphql/execution/executor.py", line 383, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: 'NoneType' object has no attribute '_meta'

```

this is my `DjangoObjectType` : 
```python
class ProductType(DjangoObjectType):
    class Meta:
        model = Product
        description = "Hey"
        filter_fields = {
            'name': ['icontains']
        }
```
and this is the query: 

```python
class Query(object):
    all_product_categories = graphene.List(ProductCategoryType)
    all_products = graphene.List(ProductType)
    filter_products = DjangoFilterListField(ProductType)
```
It is correctly connected to the rest of the project schema.

I made some debugging and it seems to be failing in [this line](https://github.com/eamigo86/graphene-django-extras/blob/master/graphene_django_extras/fields.py#L88), the `root` param is `None` 

Am I making some mistake or is this an issue for this library? 

Thanks for all the help you can provide to me.

**Comment by eamigo86** [comment]
Hi Milton thanks for report this bug. Sorry for delay. This bug is already 
fixed and will be available in next release(0.2.0) very soon , with many 
new stuff !!!


En 16 de diciembre de 2017 7:21:50 PM Milton Lenis

**Comment by eamigo86** [comment]
Hi @MiltonLn the new release is ready, please test it !!!

**Comment by MiltonLn** [comment]
Thanks a lot for your quick help @eamigo86 I'll test it ASAP
