### ISSUE TITLE
Updating to GitHub Actions' environment variables

### ISSUE THREAD

**Issue by ldynia** [eamigo86/graphene-django-extras#170]
Hi @eamigo86 

We have started working on migration from **Travis** to **GitHub Action**. We need few things from you. 

1. Update/missing GitHub Actions environment variables with TELEGRAM_TOKEN
1. Update/missing GitHub Actions environment variables with TELEGRAM_CHAT_ID

P.S
I created new branch called `actions` you will find CI/CD implementation in `.github/workflows/ci.yaml`.

**Comment by eamigo86** [comment]
Hello @ldynia, 

Sorry for the delay in answering. I have added the 2 secrets (TELEGRAM_TOKEN and TELEGRAM_CHAT_ID) to the project. 

Kind regards
