### ISSUE TITLE
Travis rewrite to GitHub Actions

### ISSUE THREAD

**Issue by ldynia** [eamigo86/graphene-django-extras#172]
Hi @eamigo86

I have finished rewriting Travis to GitHub Actions. Continuous Integration & Continuous Delivery is in place now.

What we are missing are:
- Update GitHub Actions environment secrets/variables with `PYPI_USERNAME`
- Update GitHub Actions environment secrets/variables with `PYPI_ACCESS_TOKEN`

**Important:** As for now the code for Continuous Delivery is disabled (commented). I propose to enable it, only when we reach code coverage e.g 80% or higher (we can discus what should be minimum value)

**Changes** - All changes are on `actions` branch.
- I have deleted `scripts/travis_telegram_notification.sh` file. Now notifications are handled by `notification.sh`.
- I have deleted `.travis.yml` file. We switched to GitHub Actions instead.

**Comment by eamigo86** [comment]
Hi Idynia, 

I just added the two required secrets values to the project settings.

Big Hug

**Comment by ldynia** [comment]
Thanks Ernesto :) I'll make a Pull Request (PR)
