### ISSUE TITLE
Hard dependency on `psycopg2`

### ISSUE THREAD

**Issue by basilfx** [eamigo86/graphene-django-extras#2]
In `converter.py` on line 4, fields from PostgreSQL are imported.

These fields are only available when you have the `psycopg2` module installed. This module is not listed in `setup.py`, but I think it is better to not depend on this if the user does not use PostgresQL.

**Comment by eamigo86** [comment]
Hello @basilfx, thanks for report this bug, I fix it right now and it will be available for version 0.0.1b9
