### ISSUE TITLE
How to add request.user to serializer?

### ISSUE THREAD

**Issue by legshort** [eamigo86/graphene-django-extras#21]
The codes seems not passing context to serializer when it's called.
`serializer = cls._meta.serializer_class(data=new_obj)`

I would like to add `request.user` when it tries to save, I couldn't find a way to do it.
Anyone has done this before?

**Comment by eamigo86** [comment]
Hi @legshort, this module as of version 0.3.3b1 allow custom initialization of Serializers, on **DjangoSerializerType** and **DjangoSerializerMutation**, through overwrite the **get_serializer_kwargs** function, example:
```python
class UserType(DjangoSerializerType):
    
    @classmethod
    def get_serializer_kwargs(cls, root, info, **kwargs):
        return {'context': {'request': info.context}}
    
    class Meta:
        serializer_class = UserSerializer
```

Thanks to [Pull request](https://github.com/eamigo86/graphene-django-extras/pull/14) of @jamesmcnamara
