### ISSUE TITLE
Is there a way to use DjangoListObjectType with related fields?

### ISSUE THREAD

**Issue by giovannicimolin** [eamigo86/graphene-django-extras#25]
Using DjangoListObjectType to make a filterable list doesn't make any related field available on the graphql endpoint. 

I have a related field called created_by (ForeignKey to User model) but I can't query it on DjangoListObjectField, only on DjangoObjectField. Is there any way I can do that?

**Comment by eamigo86** [comment]
Hello @giovannicimolin , could you give me an example of the query with DjangoListObjectType and DjangoObjectField, because if I should be able to access.

**Comment by EmiM** [comment]
Same for me. Example code:

```python

class Book(models.Model):
  title = models.CharField(...)
  author = models.ForeignKey(Author)

class BookListType(DjangoListObjectType):
  class Meta:
    model = Book
    only_fields = ("title", "author")

class BookQuery(object):
  all_books = DjangoListObjectField(BookListType)
```

And in this case I can only access "title" from graphql. Author relation is not available.

**Comment by eamigo86** [comment]
Ok EmiM, I will check that right now. Thanks for share your code.

**Comment by eamigo86** [comment]
Hi again @EmiM, sorry for the delay, but I had to make an urgent trip to the last minute.
Could you tell me the version of the module you are using? Because I just recreated your example and it worked perfectly.

**Comment by EmiM** [comment]
I'm using `graphene-django-extras==0.3.3`. I am able to retrieve all data except the foreign key relation. 

On the graphql side I call it like this:
```{
allBooks {
  results {
    title
    author
    }
  }
}
```

Returned error: `"Cannot query field \"author\" on type \"BookGenericType\"."`

**Comment by eamigo86** [comment]
Hi EmiN,please be shure to install last version: 0.3.4a1.
pip install graphene-django-extras==0.3.4a1

**Comment by EmiM** [comment]
@eamigo86 thank you for quick responses. I will try it with version you suggested.

**Comment by eamigo86** [comment]
Hi @EmiM. Did you try the new version that I suggested you?

**Comment by aldarund** [comment]
@eamigo86 0.3.4a2 doesnt work for me.

```
class Application(TimeStampedModel):
    ....
    applicant = models.ForeignKey(Applicant, null=True, blank=True,  on_delete=models.SET_NULL)

class ApplicationListType(DjangoListObjectType):
    class Meta:
        model = models.Application
        description = 'Application List'
        filterset_class = ApplicationFilter
        only_fields = ("id", "applicant")

class Query(graphene.ObjectType):
    list_applications = DjangoListObjectField(types.ApplicationListType)


query {
  listApplications {
    results {
      applicant
    }
  }
}


Cannot query field \"applicant\" on type \"ApplicationType\"
```

**Comment by aldarund** [comment]
@eamigo86 after debuggin code i found that its because you need to define ApplicantType.
Something like this enough, even without using it anywhere
```
class ApplicationType(DjangoObjectType):
    class Meta:
        model = models.Application
        description = 'Application'
```
Without this it will produce this error. Its quite not obvious behavior.

**Comment by eamigo86** [comment]
Hi @aldarund
This happens because you must have defined at least one type valid for each model, so the graphql engine can do a correct mapping of each of the relational fields. Otherwise, the system will assume that you do not want those models to be included in the schema generation.
