### ISSUE TITLE
Warining: Abstract type is deprecated

### ISSUE THREAD

**Issue by sgaseretto** [eamigo86/graphene-django-extras#26]
I'm getting this warning when runing my server

```

/Users/sgaseretto/.virtualenvs/graphene/lib/python3.6/site-packages/graphene/types/abstracttype.py:9: DeprecationWarning: Abstract type is deprecated, please use normal object inheritance instead.
See more: https://github.com/graphql-python/graphene/blob/2.0/UPGRADE-v2.0.md#deprecations
  "Abstract type is deprecated, please use normal object inheritance instead.\n"
/Users/sgaseretto/.virtualenvs/graphene/lib/python3.6/site-packages/graphene/types/abstracttype.py:9: DeprecationWarning: Abstract type is deprecated, please use normal object inheritance instead.
See more: https://github.com/graphql-python/graphene/blob/2.0/UPGRADE-v2.0.md#deprecations
  "Abstract type is deprecated, please use normal object inheritance instead.\n"
[14/Mar/2018 20:02:27] "POST /graphql/ HTTP/1.1" 200 72700


```

Any idea of how to avoid it?

**Comment by eamigo86** [comment]
Hi @sgaseretto, this warning is because  you have defined a class that 
inherited from AbstractType, and in version 2.0 of graphene-django this 
class is deprecated. You must inherit from ObjectType instead of AbstractType.

**Comment by sgaseretto** [comment]
Thanks for answering so quickly. I haven't inherited from AbstractType anywhere in my code, I just implemented the example you put in the README, it seems that there is a class in the graphene-django-extras package that inherits from AbstractType

**Comment by sgaseretto** [comment]
Sorry, you were right, I'm closing this issue
