### ISSUE TITLE
filtering by request data

### ISSUE THREAD

**Issue by aldarund** [eamigo86/graphene-django-extras#28]
For example i want to filter articles by current user using DjangoListObjectField or DjangoFilterPaginateListField
I dont see a clean way to do so right now. In django-graphene for DjangoConnectionField i could define resolve_articles field. It doesnt work here.
Other options would be to use django-filter request filtering by defining a custom filterset_class. https://django-filter.readthedocs.io/en/latest/guide/usage.html#filtering-the-primary-qs

But request not passed to filterset at all
https://github.com/eamigo86/graphene-django-extras/blob/master/graphene_django_extras/fields.py#L188 only qs and data passed. Something like request=info.context is missed.

Am i missing something?

**Comment by eamigo86** [comment]
Hi @aldarund, the new @bemcculley [PR](https://github.com/eamigo86/graphene-django-extras/pull/30) 
should resolve this issue.

**Comment by aldarund** [comment]
@eamigo86 thats pr what i did locally my subclassing :) Just though maybe there was a way that i missed. Anyway now its in source so all good :)
