### ISSUE TITLE
Changing some Fields from a DjangoInputObjectType to required=False

### ISSUE THREAD

**Issue by sgaseretto** [eamigo86/graphene-django-extras#31]
I'm trying to create some update mutations, where I don't want to pass some fields, because I don't want to update them.
For example I have this model:

```python
class Pet(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
```

And the following InputType:

```python
class PetInput(DjangoInputObjectType):
    class Meta:
        model = Pet
        description = 'Pet InputType'
```

How can I change, for example, the name and owner fields from my InputType in order to make them required=False. As a suggestion, it will be nice adding something like the ```exclude_fields = ('name', 'owner')``` that makes them required=False, for example a ```require_false_fields = ('name', 'owner')``` I just don't know how something like this could be implemented

**Comment by eamigo86** [comment]
Hi @sgaseretto, specifically in your case, you have to put **blank=True** in the fields of your model that you do not want to be required. For example, the following definition of your model will not generate the **owner** field as required in the graphql mutations:

```python
class Pet(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(blank=True, null=True)  
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
```
