### ISSUE TITLE
resolve_[field_name] not working for DjangoListObjectField

### ISSUE THREAD

**Issue by tadeo** [eamigo86/graphene-django-extras#34]
I've defined a simple DjangoListObjectType with just a model and pagination attributes in the Meta and when added to Query with DjangoListObjectField I can't get the resolve_[field_name] method called.
Is this an intended behavior? How can I intervene the list/queryset? I wanted to filter out some elements.
Just as a reference of my intention:

```python
class Product(models.Model):
    name = models.CharField(max_length=255)
    discontinued = models.BooleanField(default=False)


class ProductListType(DjangoListObjectType):
    class Meta:
        model = Product
        pagination = LimitOffsetGraphqlPagination()


class Query(graphene.ObjectType):
    all_products = DjangoListObjectField(ProductListType)

   def resolve_all_products(self, info, **kwargs):
      qs = Product.objects.all()
      some_parameter = kwargs.get('some_parameter')
      if some_parameter is not None:
          qs.exclude(discontinued=True)
      return qs
```

Thanks a lot!

**Comment by eamigo86** [comment]
Hi @tadeo, sorry about that, but it's a pending work that I have to do, which one will be available very soon.

**Comment by tadeo** [comment]
@eamigo86 Exploring for alternatives I found that I can use a FilterSet class where to filter the queryset through its `filter_queryset(self, queryset)` method, having the request available at self.request. Here the idea:
```python
class Product(models.Model):
    name = models.CharField(max_length=255, default=None, unique=True, verbose_name=_('name'))
    discontinued = models.BooleanField(default=False, verbose_name=_('discontinued'))


class ProductListType(DjangoListObjectType):
    class Meta:
        model = Product
        pagination = LimitOffsetGraphqlPagination()


class ProductFilter(django_filters.FilterSet):
    class Meta:
        model = Product

    def filter_queryset(self, queryset):
        self.request  # here I will be able to filter the queryset with the request (loged user, etc)
        return queryset


class Query(graphene.ObjectType):
    all_products = DjangoListObjectField(ProductListType, filterset_class=ProductFilter)
```
Gracias!

**Comment by gregbrowndev** [comment]
Hi, I also have the need for `resolve_[field]` in order to add queryset annotations to my type, which isn't quite solved by #15 , i.e:

```py
class SystemType(DjangoObjectType):

    version = graphene.Int()
    warning_count = graphene.Int()

    class Meta:
        model = System
        filterset_class = SystemFilter


class SystemListType(DjangoListObjectType):

    version = graphene.Int()
    warning_count = graphene.Int()

    class Meta:
        model = System
        pagination = PageGraphqlPagination(page_size=20)
        filterset_class = SystemFilter


class Query(object):
    systems = DjangoListObjectField(SystemListType)
    system = DjangoObjectField(SystemType)

    def resolve_systems(self, info, **kwargs):
        return System.objects\
            .add_version_number()\
            .add_warning_count()
```

Thanks!

**Comment by tadeo** [comment]
@gregbrowndev just curious, did you try the `filterset_class` workaround I suggest?

**Comment by cfp2000** [comment]
I’m also very interested in this. 

I want to use it with https://github.com/flavors/django-graphql-jwt

**Comment by gsiegman** [comment]
@tadeo I attempted your solution, however when making a GraphQL query my filterset's filter_queryset method never gets called. Is there anything additional you had to do beyond what is showing in your code above?

**Comment by aldarund** [comment]
@gsiegman http://django-filter.readthedocs.io/en/latest/guide/usage.html#filtering-the-primary-qs

**Comment by gsiegman** [comment]
@aldarund that did it, thank you!

**Comment by s3rius** [comment]
@cfarvidson, if you still interested in using `django-graphql-jwt` with this library, you can check the request #176.

**Comment by cfarvidson** [comment]
> @cfarvidson, if you still interested in using `django-graphql-jwt` with this library, you can check the request #176.

Thanks. Sadly I’ve abandoned the Django  project that I used JWT in. 🙂
