### ISSUE TITLE
Ability to add custom fields for DjangoObjectType

### ISSUE THREAD

**Issue by aldarund** [eamigo86/graphene-django-extras#35]
Right now i dont see a way to add a custom fields. Like a custom value that is based on other field values.

**Comment by Donnyyyyy** [comment]
Hello!

If you need a custom value that is based on other field values, you can simply add a field like to ``ObjectType``:

```python
class ShipmentType(DjangoObjectType):
    some_dummy_field = graphene.String()

    class Meta:
        model = MyModel

    def resolve_some_dummy_field(self, info):
        return 'Hello to {user} from {model_name}-{instance_id}'.format(
            user=info.context.user.username,
            model_name=self.__class__.__name__,
            instance_id=self.id
        )
```

**Comment by paymog** [comment]
How do I resolve a django object along with an extra, calculated field like below during a query?

```python
class ProjectType(DjangoObjectType):
    class Meta:
        model = Project

    extra_field = graphene.String()


class Query(ObjectType):
    project = graphene.Field(ProjectType,
                             name=graphene.String())

    def resolve_project(self, info, name):

        if id is not None:
            return Project.objects.get(pk=id) # how do I populate `extra_field` here?


        return None
```

**Comment by eamigo86** [comment]
Hi @paymog , you must define a resolver function for your **extra_field** inside **ProjectType** definition

```python
class ProjectType(DjangoObjectType):
    class Meta:
        model = Project

    extra_field = graphene.String()

    def resolve_extra_field(self, info):
        if self is not None:
            return self.name.upper()      # self is the current Project object
        return ''


class Query(ObjectType):
    project = graphene.Field(ProjectType,
                             name=graphene.String())

    def resolve_project(self, info, name):
        if id is not None:
            return Project.objects.get(pk=id) # how do I populate `extra_field` here?

        return None
```

**Comment by paymog** [comment]
Oooh, cool. Thanks @eamigo86!

**Comment by paymog** [comment]
@eamigo86 any chance you know how to conditionally resolve the extra field? The field I need to calculate requires lots of time to compute and I was hoping I could add a flag to the Query which decides whether or not to calculate the field. I was imagining something like:

```python
class ProjectType(DjangoObjectType):
    class Meta:
        model = Project

    extra_field = graphene.String()

    def resolve_extra_field(self, info):
        if self is not None:
            return self.name.upper()      # self is the current Project object
        return ''


class Query(ObjectType):
    project = graphene.Field(ProjectType,
                             name=graphene.String(),
                             compute_extra_field=graphene.Boolean())

    def resolve_project(self, info, name, compute_extra_field):
        if name is not None:
            # use the value of compute_extra_field to determine whether extra_field should be None or computed. 
            # Can this flag somehow be passed to the resolve_extra_field function?
            return Project.objects.get(name=name) 
        return None
```

**Comment by paymog** [comment]
For anyone who comes across this in the future, some testing tells me that `resolve_extra_field` isn't called unless the client requests `extra_field` in their query.

**Comment by a-c-sreedhar-reddy** [comment]
> Hi @paymog , you must define a resolver function for your **extra_field** inside **ProjectType** definition
> 
> ```python
> class ProjectType(DjangoObjectType):
>     class Meta:
>         model = Project
> 
>     extra_field = graphene.String()
> 
>     def resolve_extra_field(self, info):
>         if self is not None:
>             return self.name.upper()      # self is the current Project object
>         return ''
> 
> 
> class Query(ObjectType):
>     project = graphene.Field(ProjectType,
>                              name=graphene.String())
> 
>     def resolve_project(self, info, name):
>         if id is not None:
>             return Project.objects.get(pk=id) # how do I populate `extra_field` here?
> 
>         return None
> ```

Hi to call a method declared in the model should I query model using `self.id` and call method on that?
