### ISSUE TITLE
DRF 3.8 Compatibility

### ISSUE THREAD

**Issue by dreglad** [eamigo86/graphene-django-extras#36]
Upgrading to the recently released [DRF 3.8.x series](http://www.django-rest-framework.org/topics/release-notes/#38x-series) broke compatibiliy with **graphene-django-extras**

In DRF 3.8, `rest_framework.compat._resolve_model` function has been removed, but it is being imported by [utils.py#L15](https://github.com/eamigo86/graphene-django-extras/blob/master/graphene_django_extras/utils.py#L15).

I don't feel like opining on the "correct" solution, but since `_resolve_model` is only used when Django < 1.9, then making it not only '_conditionally used_' but also '_conditionally imported_' would make sense to me.

**Comment by jzelez** [comment]
I've made a PR for a quick & dirty solution #37

**Comment by eamigo86** [comment]
Thanks @jzelez. Good job
