### ISSUE TITLE
(Custom) Django filters not applied

### ISSUE THREAD

**Issue by basilfx** [eamigo86/graphene-django-extras#4]
In `fields.py` in the method `list_resolver` (around line 227), I see that `filterset_class` is commented out and not used at all.

This prevents one from applying custom filters from django_filter. For instance, I have the following filter:

```python
class ObjectFilter(django_filters.FilterSet):
    class Meta:
        model = models.Object
        fields = ["id"]

    # sort is not a field on models.Object, it's just a name I have chosen.
    sort = django_filters.OrderingFilter(fields=(
        'id', 'created',
    ))
```

The problem is that `sort` is not a field that exists on the `Object` model, but `queryset_factory` tries to apply this one in the `filter(**kwargs)` method of a model.

This generates errors such as: 

```graphql.error.located_error.GraphQLLocatedError: Cannot resolve keyword 'sort' into field. Choices are: id, created```

So it should apply the filterset class, and ensure that non-model fields are not passed to the `filter(**kwargs)` method.

**Comment by basilfx** [comment]
I have changed the following (not sure if it works according to your ideas):

In `fields.py` around line 227:

```python
def list_resolver(self, manager, filterset_class, filtering_args, root, info, **kwargs):
    qs = queryset_factory(manager, info.field_asts, filtering_args, **kwargs)
    filter_kwargs = {k: v for k, v in kwargs.items() if k in filtering_args}

    qs = manager.get_queryset()
    qs = filterset_class(data=filter_kwargs, queryset=qs).qs
    count = qs.count()

    return DjangoListObjectBase(
        count=count,
        results=qs,
        results_field_name=self.type._meta.results_field_name
    )
```

In `utils.py` around line 113:

```python
def queryset_factory(manager, fields_asts=None, filtering_args=None, **kwargs):

    if filtering_args is None:
        filtering_args = {}
    select_related = []
    prefetch_related = []
    filter_kwargs = {k: v for k, v in kwargs.items() if k in filtering_args}
    available_related_fields = get_related_fields(manager.model)

    for f in kwargs.keys():
        temp = available_related_fields.get(f.split('_', 1)[0], None)
        if temp:
            if (temp.many_to_many or temp.one_to_many) and temp.name not in prefetch_related:
                prefetch_related.append(temp.name)
            else:
                select_related.append(temp.name)

    if fields_asts:
        select_related, prefetch_related = recursive_params(fields_asts[0].selection_set, available_related_fields, select_related, prefetch_related)

    if select_related and prefetch_related:
        return manager.select_related(*select_related).prefetch_related(*prefetch_related)
    elif not select_related and prefetch_related:
        return manager.prefetch_related(*prefetch_related)
    elif select_related and not prefetch_related:
        return manager.select_related(*select_related)
    return manager
```

I basically removed all `filter(**kwargs)` calls from the `queryset_factory` and moved them back to the `list_resolver` method.

**Comment by eamigo86** [comment]
Hello again @basilfx. First of all I would like to thank you very much for your comments and for your help. This bug, like the other two, will already be used from version 0.0.1b9.

![image](https://user-images.githubusercontent.com/11740026/31103876-0f016d20-a79f-11e7-9ba7-3e9a18a92695.png)

**Comment by basilfx** [comment]
@eamigo86 Thanks for fixing. I will continue to evaluate this and submit ideas/bugs/comments to further improve this great package!
