### ISSUE TITLE
drf removed compat._resolve_model in latest update

### ISSUE THREAD

**Issue by jstacoder** [eamigo86/graphene-django-extras#40]
this commit https://github.com/encode/django-rest-framework/commit/06e2ad0b7dfb78635aa0e58fa887c7e27f0e17b8 was recently merged into master in drf breaking `ExtraGraphQLView`

**Comment by grahammcculloch** [comment]
I also ran into this problem. Had to explicitly require `djangorestframework==3.7.7`.

**Comment by eamigo86** [comment]
Hello everyone and thank you very much for report this compatibility error.
Sorry for the delay, but I was super short on time. Right now I have started working on a new release that will bring a few improvements and new features.
But for the moment, to avoid this error, work with the last dev version:
```python
pip install graphene-django-extras==0.3.8a2
```
Thank you
