### ISSUE TITLE
How can I use the decorators in django-graphql-jwt ?

### ISSUE THREAD

**Issue by cidylle** [eamigo86/graphene-django-extras#41]
I am using [django-graphql-jwt](https://github.com/flavors/django-graphql-jwt) and it exposes a couple of decorators such as `@login_required` that are used to decorate the resolver functions to restrict their access. 

How can I use such decorators with `DjangoSerializerType`, `.ListField()`, `RetrieveField()`, etc. I only want to restrict access for certain fields such as: 

```
import graphene
from .types import UserType


class Query(graphene.ObjectType):
    users = UserType.ListField()
    user = UserType.RetrieveField()


class Mutation(graphene.ObjectType):
    update_user = UserType.UpdateField()
```

Resolvers are not defined in these cases. Any suggestions on how to make it work with `django-graphql-jwt` ?

**Comment by soosap** [comment]
Hi this is a very good question. I am asking this myself too. I have enjoyed using `DjangoFilterListField` in a testing setup. But I cannot use it in production due to being unable to apply custom logic when to actually fulfil the request and when not to.

In the graphene-django space I can do this:

```py
class Query(graphene.ObjectType):
    words = graphene.List(WordType, query=graphene.String())

    @is_authenticated
    def resolve_words(self, info, **kwargs):
        # only gets here if authentication succeeds
        words = Word.objects.all()
        return words
```

I can add the `icontains` and `iexact` filtering power by just doing this (which is really amazing):
```py
class Query(graphene.ObjectType):
    words = DjangoFilterListField(WordType)
```

But I lose the ability to apply decorators. Can you advise how we could overcome this?

**Comment by jstacoder** [comment]
Any progress on this? Or can you point me in the right direction to do it, if it’s still waiting to be done?

**Comment by emad-ir** [comment]
Going through the same struggle. Any help would be appreciated

**Comment by emad-ir** [comment]
@eamigo86 @jstacoder Will you please advice a solution?

**Comment by jstacoder** [comment]
@emad-ir playing with this more i realized overloading the class's `list_resolver` method is the way to go here, you also get access to override the default `filtering_args` for the `filterset` something like this: 

```python
class MyListObjectField(DjangoFilterListField):
    @login_required
    def list_resolver(self, manager, filterset_class, filtering_args, root, info, **kwargs):
        return super(MyListObjectField, self).list_resolver(manager, filterset_class, filtering_args, root, info, **kwargs)
```

then in your `Query`:

```python
class Query(graphene.ObjectType):
    list_my_object = MyListObjectField(MyListObjectType)
```

**Comment by Kendysond** [comment]
Thanks @jstacoder ! This really helps!

**Comment by kawasakikou** [comment]
Thanks @jstacoder!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jstacoder** [comment]
> Thanks @jstacoder!!!!!!!!!!!!!!!!!!!!!!!!!!!

np

**Comment by BenjjinF** [comment]
@jstacoder this solution works if your models don't have any foreign key fields which the user isn't permitted to view. I haven't been able to find a way to do a permissions check per-field.

**Comment by killinit** [comment]
@jstacoder  
please provide a full example.

**Comment by Cimmanuel** [comment]
Did anyone properly implement this?

**Comment by IdemenB** [comment]
Hello everyone, what's the positioning of AuthenticatedGraphQLView in all these discussions? There is no reference to it in the documentation at all. Any advice and experience on authentication and authorization for both Queries and Mutations implementing this library would be highly appreciated.

**Comment by IdemenB** [comment]
> @emad-ir playing with this more i realized overloading the class's `list_resolver` method is the way to go here, you also get access to override the default `filtering_args` for the `filterset` something like this:
> 
> ```python
> class MyListObjectField(DjangoFilterListField):
>     @login_required
>     def list_resolver(self, manager, filterset_class, filtering_args, root, info, **kwargs):
>         return super(MyListObjectField, self).list_resolver(manager, filterset_class, filtering_args, root, info, **kwargs)
> ```
> 
> then in your `Query`:
> 
> ```python
> class Query(graphene.ObjectType):
>     list_my_object = MyListObjectField(MyListObjectType)
> ```

Hi @jstacoder , do you think in order to be able to use decorators, the correct method to overwrite is perform_mutate for mutations done through DjangoSerializerMutation ?

**Comment by IdemenB** [comment]
I think I've found the solution, dependign on the use case, .create, .update or .delete methods of the DjangoSerializerMutation can be overridden in order to apply JWT authorizations. Here is a sample code:

class UserSerializerMutation(DjangoSerializerMutation):

Note: In this sample only update mutation is restricted.


   ```

class Meta:
        description = "DRF serializer based Mutation for User instances"
        serializer_class = UserSerializer
        include_fields = ('id',)

        # input_field_name = "new_user_data"
        # nested_fields = True

    @classmethod
    def update(cls, root, info, **kwargs):
        user = info.context.user
        if user.is_anonymous:
            raise Exception(
                _('You must be authorized in order to perform the update operation!'))
        else:
            return super().update(root, info, **kwargs)

class Mutation(graphene.ObjectType):

    user_create = UserSerializerMutation.CreateField()
    user_delete = UserSerializerMutation.DeleteField()
    user_update = UserSerializerMutation.UpdateField() 
```
