### ISSUE TITLE
mixed prefetch_related() and select_related()

### ISSUE THREAD

**Issue by dreglad** [eamigo86/graphene-django-extras#43]
Hi @eamigo86, thanks for sharing this!

I was struggling with Django ORM errors like:
> Invalid field name(s) given in select_related: 'my_field'. Choices are: my_other_field, another_one, ...

 In particular, this happens when both querying AND filtering by a many-to-many or one-to-many relation field.

If i'm not missing something, there seems to be a subtle bug over `utils.recursive_params()` that leads to such fields being used as arguments for `prefetch_related` (expected) and simultaneously for `select_related` (unexpected) if they're "visited" more than once within the recursion.

I made a pull request #42 which fixes this issue for me, by adjusting [this](https://github.com/eamigo86/graphene-django-extras/blob/master/graphene_django_extras/utils.py#L278) duplicate-preventing conditional that misidentifies already-added fields meant for `prefetch_related` as fields meant for `select_related`.

**Comment by eamigo86** [comment]
Hi @dreglad, thank you very much for the contribution, sure to be of great help, this part of the code intended to avoid the N + 1 queries is a bit tedious and needs some optimization even. regards

**Comment by sulabhjain** [comment]
Hi @eamigo86, I ran into this issue while trying to find a way to avoid N+1 queries. I am not sure if this is the right forum to address this question ?

I have a use case similar to the one below. I am fetching orders list and each order belongs to a product where each product can be put into multiple categories which I am trying to list along side product details (yes this is 3 level nested..). Each product as part of orders fetched initiates a query to fetch categories resulting jn N+ 1 query.  I am not sure if there is already a built in way in the library to optimize N+1 queries. Any code sample is highly appreciated ?

FYI: I have been trying to evaluate as well if [graphene-django-optimizer](https://github.com/tfoxy/graphene-django-optimizer) library would fit in along side graphene-django-extras to solve this problem. Please let me know your opinion ?

`
query { orders {
    results {
       product {
          categories {
              id
              name
          }
       }
    }
}
}
`

**Comment by eamigo86** [comment]
Hi @sulabhjain, I am aware that the function responsible for optimizing queries and avoiding N + 1 queries is not working as it should.
I am currently working on a more efficient solution.
The other module that you mention looks good, but I do not know what degree of integration you would have with this package.

**Comment by fabioanderegg** [comment]
Another workaround to add select_related and prefetch_related is to override the list_resolver method from the DjangoListObjectField class:
```python
class NetworkDeviceListObjectField(DjangoListObjectField):
    def list_resolver(self, *args, **kwargs):
        base = super().list_resolver(*args, **kwargs)
        qs = base.results
        qs = qs.prefetch_related('interfaces')
        base.results = maybe_queryset(qs)
        return base

class Queries(graphene.ObjectType):
    network_devices = NetworkDeviceListObjectField(NetworkDeviceListType)
```
A nice API to do this would obviously better in the long term.

**Comment by cramshaw** [comment]
Hi!
I came across this dealing with the exact same problem, for anyone else who does, my solution inspired by @fabioanderegg was to use graphene-django-optimizer:

```
class CustomDLOF(DjangoListObjectField):
    def list_resolver(self, *args, **kwargs):
        base = super().list_resolver(*args, **kwargs)
        qs = base.results
        base.results = gql_optimizer.query(qs, args[-1])
        return base
```
