### ISSUE TITLE
Idea: expose more details on pagination

### ISSUE THREAD

**Issue by basilfx** [eamigo86/graphene-django-extras#5]
This is something that can be useful for pagination:

* Allow an option to limit the maximum number of results per offset/page query, e.g. `PageGraphqlPagination(max_limit=100)`. This way, someone cannot query all the results.
* Expose the actual limit that is being applied.

Consider this (dangerous) query:

```graphql
allUsers() {
    results(limit:9999, offset:5) {
      ...
    }
    totalCount
    limit <-- return the actual limit that is used.
  }
}
```

Without this information, you cannot calculate the right number of pages, because if you assume that you can request 99,999 items, and there are 1,000 items, you would calculate 1 page. But if the server applies a limit (e.g. 100), there is no way that you can determine the number of pages (1,000).

**Comment by eamigo86** [comment]
Hi @basilfx, I will work to make the configuration of the page more friendly, in the next days I will update the module with the changes and I will let you know.
Thanks for the suggestions that will always be welcome. regards

**Comment by eamigo86** [comment]
Hi @basilfx, I have uploaded a new version (**0.0.1rc2**) with the possibility of choosing the pagination type and the number of elements of each page in a global way, that is to say from a configuration in the settings.py, I still have to update the documentation (I'm lazy doing it), but in essence it can be configured like this:
```python
GRAPHENE_DJANGO_EXTRAS = {
    # Default Pagination: None
    'DEFAULT_PAGINATION_CLASS': "graphene_django_extras.pagination.LimitOffsetGraphqlPagination",

    # Default: None
    'PAGE_SIZE':  100,
}
```

Regardless of pagination type, you will see in the parameter description the values of the default limits and the maximum limit of the each page size, example para **LimitOffsetGraphqlPagination**:
![image](https://user-images.githubusercontent.com/11740026/31250841-b3e1afe6-a9e1-11e7-82f6-5f6f6e654880.png)

These parameters can be configured by specifying the pagination in each **DjangoObjectListType**:
![image](https://user-images.githubusercontent.com/11740026/31251002-2f39c854-a9e2-11e7-8f62-298639b90ca0.png)

In this case (**LimitOffsetGraphqlPagination**), if the **_max_limit_** value is not specified when defining the pagination type in the subclass definition **DjangoObjectListType**, the query will return **_None_**, just as it happens in the **DjangoRestFramework** module.

Similarly if you try to set a **_limit_** that is greater than the defined _**max_limit**_ or not specify at all, the size of the paginate will be the one specified in the value of **_max_limit_**:
![image](https://user-images.githubusercontent.com/11740026/31251601-212f7d10-a9e4-11e7-9a5d-a12a2957a2ef.png)

It is difficult to return the actual limit (page size) that is used to the request as you suggested, I will continue to look for an optimal way to give that possibility, for now this is everything.

**Comment by basilfx** [comment]
Tested the new option, and it works like a charm. I did not use the settings in `settings.py`, but just in the constructor itself.
