### ISSUE TITLE
PyPi package out of date (Last Released: May 10)? Directive import in README updated recently

### ISSUE THREAD

**Issue by kennandavison** [eamigo86/graphene-django-extras#57]
Hi,

Hope this issue helps others out. I was trying to import all_directives like in the README and getting an error since it hasn't been updated on PyPi.

I can resolve this by installing directly from GitHub/installing 0.3.8a8, but it'd probably make sense to update the PyPi package/make a note on the README.

**Comment by eamigo86** [comment]
Hi @kennandavison, the last version in PyPi repository is [0.3.8a9](https://pypi.org/project/graphene-django-extras/0.3.8a9/), but being alpha versions, when you do:
```python
 pip install graphene_django_extras
```
 The pip package allways installs the last stable version (0.3.7), which is the last one that is described in the readme. 
Currently I am working on a new version that will bring many new things in addition to fixing most of the reported issues. Thank you
