### ISSUE TITLE
How can i override delete method 

### ISSUE THREAD

**Issue by warm200** [eamigo86/graphene-django-extras#59]
Hi,
Thanks for the lib, i like it very much, 
quick question is, seems i can't override the delete method,
I want to check if the products owned by current logged in user before i delete it.
but it seems it's never calling delete and never print product in the console, 
create, and update working fine
```
from rest_framework import serializers
from core.models import Product
class ProductSerializer(serializers.Serializer):
     class Meta:
            model = Product
    def create(self, validated_data):
           pass
    def update(self, product, validated_data):
           pass
     def delete(self, product):
            if self.logged_in() and product.user.id == self.user().id:
                print("product", product)
            raise ValidationError(message={"message": "user not logged in"})
```

**Comment by eamigo86** [comment]
Hi, @warm200 , the Serializer class have not a delete method, but if you use DjangoSerializerMutation or DjangoSerializerType to define your types and mutations, you can overwrite the delete method:

```python 
@classmethod
def delete(cls, root, info, **kwargs):
    # here your logic before delete object
    super().delete(root, info, **kwargs)
```
