### ISSUE TITLE
DjangoInputObjectType problem and nested serializers

### ISSUE THREAD

**Issue by Magni77** [eamigo86/graphene-django-extras#6]
Hi. Thanks for implementing this stuff. I'm playing around with graphene some time and get piss off on things that were easy in DRF. 
I've got problem with implementing DjangoInputObjectType.
This is what i get after just copy-pasting code example:

`    super(InputObjectType, cls).__init_subclass_with_meta__(_meta=_meta, interfaces=interfaces, **options)
TypeError: __init_subclass_with_meta__() got an unexpected keyword argument 'interfaces'
`

Also, i was trying to implement nested serializer like this:
http://www.django-rest-framework.org/api-guide/serializers/#writable-nested-representations
but it doesn't seem to do anything. Is it even posible?

**Comment by eamigo86** [comment]
Hi @Magni77, could you attach me your traceback to get more information about the error?

**Comment by eamigo86** [comment]
Hi @Magni77 your issue it fixed on lasted version: [**0.0.1**](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.0.1)
