### ISSUE TITLE
Work together with django-hvad

### ISSUE THREAD

**Issue by borsden** [eamigo86/graphene-django-extras#64]
Is there any good way to start working with django-hvad? 
What i found: it create translations_model attribute in _meta of model. So, minimum we must include fields from this model in _meta.fields.  
In my opinion, there is no obvious way to add fields from this model. Of course, we can do it manually for all required fields and resolve them from this model, but i think that it is not pretty. 
Also, i tried monkeypatch `get_model_fields` something like this 
```
old_get_model_fields = converter.get_model_fields
def get_model_fields(model):
    fields = old_get_model_fields(model)
    if hasattr(model._meta, 'translations_model'):
        fields += old_get_model_fields(model._meta.translations_model)
    return fields
converter.get_model_fields = get_model_fields
```
and then i can get fields of translation model and use it in query as normal. But i do not check something like mutations and monkeypatching also is not good way.
So, how make it more clearly?

**Comment by eamigo86** [comment]
Hi @borsden, this seems a very good extension to make compatible but as I see it has no compatibility with Django> = 2.0 and that's not good? Do you have any information about it?

**Comment by borsden** [comment]
I know about this issue (https://github.com/KristianOellegaard/django-hvad/issues/344), but last action there was one year ago. Maybe you right, and it is not a good idea to try support legacy extension. 
My previous idea with monkeypatching does not work, because i got something like this: 
"Accessing translated fields like {model_name}.{field_name} from an regular model requires a translation-aware queryset, For regular, non-translatable models, you can get one using hvad.utils.get_translation_aware_manager". I tried several ways to solve it, but they all looks ugly.
So, i decided to stop on something like this 
```
from graphene_django_extras import DjangoObjectType
from graphene_django_extras.converter import construct_fields
from graphene_django_extras.registry import get_global_registry


class DjangoHvadObjectType(DjangoObjectType):
    class Meta:
        abstract = True

    @classmethod
    def __init_subclass_with_meta__(
        cls,
        model=None,
        registry=None,
        only_fields=(),
        exclude_fields=(),
        **kwargs
    ):
        """Use this class for django-hvad models. Check, that it is TranslatableModel, then use model
        `model._meta.translations_model` as main model. Also manually resolve fields from main model.
        """
        assert hasattr(model._meta, 'translations_model'), (
            'You need to pass a TranslatableModel model (django-hvad) in {}.Meta, received "{}".'
        ).format(cls.__name__, model)
        translations_model = model._meta.translations_model

        if not registry:
            registry = get_global_registry()

        for name, field in construct_fields(model, registry, only_fields, ('id', 'translations') + exclude_fields).items():
            # Dynamic add resolvers for all fields from main model.
            def resolve_name(self, info, **kwargs):
                return getattr(self.master, name)

            setattr(cls, name, field)
            setattr(cls, 'resolve_{}'.format(name), resolve_name)

        super().__init_subclass_with_meta__(
            model=translations_model,
            registry=registry,
            only_fields=only_fields,
            exclude_fields=exclude_fields,
            **kwargs
        )
``` It also looks like my nightmare, but i don't want to continue touch it)

**Comment by borsden** [comment]
Okey, finally i decide use django-parler insead of django-hvad, because it is too horrible)

**Comment by rapita** [comment]
Hi @borsden 
Please give your example of using django-graphene with django-parler
