### ISSUE TITLE
Dumb question for __init_subclass_with_meta__

### ISSUE THREAD

**Issue by warm200** [eamigo86/graphene-django-extras#67]
Hi Sir,
Much appreciate for the lib you are working on!  i like it very much.
I wonder if you can give me some guidance on how __init_subclass_with_meta__ works, 
i keep investigating in the source code and other examples but still can't figure it out.

in this method: 

```@classmethod
    def __init_subclass_with_meta__(cls, serializer_class=None, only_fields=(), exclude_fields=(),
                                    save_resolver=None, delete_resolver=None,
                                    input_field_name=None, output_field_name=None, description='',
                                    nested_fields=False, **options):

        if not serializer_class:
            raise Exception('serializer_class is required on all DjangoSerializerMutation')
```

the point confused me is I didn't find anywhere that __init_subclass_with_meta__ get called as a classmethod in my code, 
and never manually pass serializer_class into this function, wonder how does line `  if not serializer_class: ` working properly? why it can automatically detect i assigned serializer_class in my Meta subclass in which inherited from DjangoSerializerMutation class? 

much appreciated!

**Comment by eclar** [comment]
Hi,

Take a look over graphene code :) The objects from this library inherit from graphene.

here for instance: https://github.com/graphql-python/graphene/blob/master/graphene/types/interface.py#L28

**Comment by Musbell** [comment]
Hello!
@eclar @warm200 Do any of you have anidea on how to fix this: [__init_subclass_with_meta__() got an unexpected keyword argument 'fields'](https://github.com/eamigo86/graphene-django-extras/issues/92)

**Comment by eamigo86** [comment]
Hi @Musbell, look [this](https://github.com/eamigo86/graphene-django-extras/issues/92#issuecomment-448199479).
