### ISSUE TITLE
undocumented feature: defining a DjangoObjectType as baseType for DjangoListObjectType or DjangoSerializerType

### ISSUE THREAD

**Issue by bwimmerl** [eamigo86/graphene-django-extras#68]
Hi,
first of all: awesome package!
I don't really have an issue to report, but a feature that should be documented and was hard for me to find.
My problem was that I intended to use DjangoSerializerType for common queries and mutations. Everything worked fine, apart from including property functions from the django model. I had to define a baseType like this, which worked fine:

```
class InstrumentType(DjangoObjectType):
    is_at = graphene.Field(LocationType.object_type(), source='is_at')
    class Meta:
        model = Instrument
```

But then I couldn't use the nice features of DjangoSerializerType or DjangoListObjectType. Then I searched for a long time how to pass that InstrumentType to e.g. a DjangoSerializerType. Finally I found out that you use this line in the types.py to get an already defined baseType from the registry:
```
output_type = registry.get_type_for_model(model)
if not output_type:
     output_type = factory_type('output', DjangoObjectType, **factory_kwargs)
```

But this depends on the order of the type definitions in the source code and is real implicit behaviour.
After I found that out, I could use my InstrumentSerializerType with correct custom baseType just like this:

```
class InstrumentSerializerType(DjangoSerializerType):
    class Meta:
        serializer_class = InstrumentSerializer
```

I really suggest you document that behaviour, since it's a powerful feature and can also have unexpected negative effects if you don't know about. 

Thanks for the nice work,
Greets,
Bene

**Comment by eamigo86** [comment]
Hi @bwimmerl, thanks for write. You are right, only that sometimes we pass details when writing the documentation of some feature and we assume that whoever reads it will not have problems with these details.
Right now, in my free time, I'm working on a new version of graphene-django-extras with many new features implemented, many issues reported corrected and it will no longer be necessary to define the DjangoObjectType base class to achieve what you propose. Anyway, thanks for the recommendation

**Comment by bwimmerl** [comment]
Alright :) Do you know when your new version might be finished?

**Comment by eamigo86** [comment]
from 10 to 15 days approximately
