### ISSUE TITLE
`get_related_model` cannot be imported

### ISSUE THREAD

**Issue by basilfx** [eamigo86/graphene-django-extras#7]
In Django Rest Framework 3.7.0 (released a few days ago), the above method is removed (see [here](https://github.com/encode/django-rest-framework/commit/c674687782ef96a3bb8466b412e99debd3d04f00#diff-ce493f71b3679e91b72126c168670399)).

Reverting back to 3.6.0 fixes it, for now.

**Comment by eamigo86** [comment]
This is because as of version 3.7.0, DRF will no longer support Django <= 1.9, even when Django 1.8 will have official support until April 2018. There will be no choice but to migrate, but for now will maintain dependency of DRF == 3.6.4.  :confused:
