### ISSUE TITLE
Objects in results array should not be nullable

### ISSUE THREAD

**Issue by dperetti** [eamigo86/graphene-django-extras#8]
This a minor but annoying issue when you use a front end tool like Apollo because it results in weaker typing.
It affects graphene-django as well, but I have more confidence in graphene-django-extras to fix it ! :-)
Here it is: results should not be of the form `results: [UserType]` but `results: [UserType!]` since returned objects in the array can't be null.
I don't know if it's somehow related, but the same issues applies to related objects resulting from foreign keys or M2M.

**Comment by eamigo86** [comment]
Hi @dperetti, Could you teach me an example of what you explain of nullable objects in results array, with a query and the resulting payload to be able to have a more exact idea of where to look for the problem?

**Comment by dperetti** [comment]
See https://github.com/apollographql/apollo-codegen/issues/225 and the final explanation.
The problem is graphene-django returns arrays of instances as `[SomeDjangoModelnstanceType]`. But the fact that a SomeDjangoModelnstanceType can't be null is not enforced. As a result, front end strict type checking tools like Flow consider that SomeDjangoModelnstanceType can potentially be null, yielding annoying warnings.
There is no way that a Django query can return an array of null objects ([None, None, None...]).
So this should be enforced somehow, probably with a NonNull graphene marker on each instance so  the return type of the array would be `[SomeDjangoModelnstanceType!]` (notice the exclamation mark!).

**Comment by eamigo86** [comment]
Hi @dperetti, please look at this image and tell me if it is what you are referring to in this issue:
![issue_8_dperreti](https://user-images.githubusercontent.com/11740026/32912616-9ec544f2-cadd-11e7-8798-cbfb7c76ada6.png)
Note that the 2 queries are identical, only that the processing of the resulting payload is different

**Comment by dperetti** [comment]
This is most likely related, but in your example, what does the GraphiQL Docs tab say about userPermissions ?
