### ISSUE TITLE
Query many-to-many relations

### ISSUE THREAD

**Issue by zurek11** [eamigo86/graphene-django-extras#88]
Query DjangoListObjectType does not resolve many_to_many relations from django-mapping. 
Example:
```
query{
  users(surname: "s"){
    results(limit: 5, offset: 2, ordering: "name"){
      id
      name
      surname
      userwalletSet{
        balance
        wallet{
          name
        }
      }
    }
  }
}
```
Wallet model has Foreign key to User. When I was using pure graphene, this userwalletSet was working. It connected all wallets related to users by their id. Why it does not work here? Any solutions? Thank you so much.

**Comment by eamigo86** [comment]
Hi @zurek11 , Could you provide me with the models associated with the error you mention?
