### ISSUE TITLE
Filter implementation with reverse foreign key

### ISSUE THREAD

**Issue by RickLazaretto** [eamigo86/graphene-django-extras#89]
Hello.  I want to implement filter to my query which list users with some relations which I will explain in models:

     class User(AbstractBaseUser, PermissionsMixin):  
      
        class Meta:  
            app_label = 'core'  
    	    db_table = 'users'  
    	    default_permissions = ()  
      
        uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=False)  
        personal_numb = models.IntegerField(null=True)  
        username = models.CharField(max_length=50, unique=True, null=False)  

Of course User has more fields, but for this explanation they are useless. 

    class Wallet(models.Model):  
      
        class Meta:  
            db_table = 'wallets'  
            app_label = 'core'  
            default_permissions = ()  
      
        name = models.CharField(max_length=50, null=False)  

And last model is UserWallet connecting user and wallet.

    class UserWallet(models.Model):  
      
        class Meta:  
            db_table = 'user_wallets'  
            app_label = 'core'  
            default_permissions = ()  
      
        balance = models.IntegerField(null=False)  
        wallet = models.ForeignKey(Wallet, null=False, on_delete=models.CASCADE, related_name='wallet_user')  
        user = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='user_wallet') 

I need to list all users with balance of all their wallets. It's working like this.
#### query:

    query{
      users(
        offset: 3, 
        limit: 1
      ){
    		userWallet{
          balance
          wallet{
            name
          }
        }
      }
    }
#### and response:

    {
      "data": {
        "users": [
          {
            "userWallet": [
              {
                "balance": 200,
                "wallet": {
                  "name": "BonusWallet"
                }
              }
            ]
          }
        ]
      }
    }
but what if i want to filter users by their **wallets balance**?

I made **UserFilter** class and **UserType** class like this:

    class UserType(DjangoObjectType):  
        class Meta:  
            model = User  

    class UserFilter(django_filters.FilterSet):  
        class Meta:  
            model = User  
            fields = {  
              'user_wallet__balance': ['gt', 'lt', 'iexact']  
            }  
           
  Query looks like this: 

    class GetUsers(object):  
        users = DjangoFilterPaginateListField(  
            UserType,  
            filterset_class=UserFilter,  
      )

And that's all. Very simple. But when i want to filter to that same example query whis is above:

    query{
      users(
        offset: 3, 
        limit: 1
        userWallet_Balance_Gt: 100
      ){
    		userWallet{
          balance
          wallet{
            name
          }
        }
      }
    }

response is:

    {
      "data": {
        "users": []
      }
    }

but that user has balance 200 like in example above. Why it will returns empty list? And when i will change offset to zero and list all 4 users (only last has wallet others not.) it will raise this error:

    {
      "errors": [
        {
          "message": "Invalid field name(s) given in select_related: 'user_wallet'. Choices are: (none)"
        }
      ],
      "data": {
        "users": null
      }
    }

Please anyone know what I doing wrong? Or if this is some sort of bug? Thank you so much.

**Comment by eamigo86** [comment]
Hi @RickLazaretto, sorry for big delay, you must read the README to understand how to define filters to the Types in graphql and how they are used with Fields.
If you still need help, please do not hesitate to contact me

**Comment by IdemenB** [comment]
@RickLazaretto  hi, did you find what you were looking for here? I am after the exact filtering need, unfortunately putting foriegn key fields by double underscore into the 'filter_fields' attribute results in "'Meta.fields' contains fields that are not defined on this FilterSet" error.
