### ISSUE TITLE
Returning TypeError when using  DjangoSerializerType:

### ISSUE THREAD

**Issue by Musbell** [eamigo86/graphene-django-extras#92]
I tried using the latest dependencies version and I keep having this error when using the `DjangoSerializerType`:
```python
TypeError: __init_subclass_with_meta__() got an unexpected keyword argument 'fields'
```

Any idea why I stumble this error?

_Originally posted by @bgsuello in https://github.com/eamigo86/graphene-django-extras/pull/90#issuecomment-444369442_

**Comment by Musbell** [comment]
How can the above stated issue be fixed?

**Comment by fabioanderegg** [comment]
Hi, I got the same error and fixed it the following way: You have to define a class deriving from DjangoObjectType AND DjangoListObjectType. E.g.:
```python
class UserType(DjangoObjectType):
    class Meta:
        model = User
        description = " Type definition for a single user "
        filter_fields = {
            'id': ['exact', ],
            'first_name': ['icontains', 'iexact'],
            'last_name': ['icontains', 'iexact'],
            'username': ['icontains', 'iexact'],
            'email': ['icontains', 'iexact']
        }

class UserListType(DjangoListObjectType):
    class Meta:
        description = " Type definition for user list "
        model = User
        pagination = LimitOffsetGraphqlPagination(default_limit=25, ordering="-username")

# schema
class Queries(graphene.ObjectType):
    users = DjangoListObjectField(UserListType, description=_('All Users query'))
```

Commenting out the UserType class gives the error above, even when UserType is not referenced anywhere. Looks like some graphene black magic happening here.

@eamigo86: Is this behaviour intended?
